from openpilot.selfdrive.car.honda.values import CarControllerParams

# acceleration

# ISO 15622:2018
MAX_ISO_ACCEL_LOW_SPEED = 4.0 # m/s^2
MAX_ISO_ACCEL_STEADY_STATE = 2.0 # m/s^2
ISO_MAX_VALS = [MAX_ISO_ACCEL_LOW_SPEED, MAX_ISO_ACCEL_LOW_SPEED, MAX_ISO_ACCEL_STEADY_STATE]

# Modified by FP
ISO_MAX_VALS_PEDAL_ACCEL_MAX = [MAX_ISO_ACCEL_LOW_SPEED, MAX_ISO_ACCEL_LOW_SPEED, CarControllerParams.PEDAL_ACCEL_MAX]

# velocity

# ISO 15622:2018
ISO_VELOCITY_START = 0. # m/s
ISO_VELOCITY_TRANSITION = 5. # m/s
ISO_VELOCITY_STEADY_STATE = 20. # m/s
ISO_MAX_BP = [ISO_VELOCITY_START, ISO_VELOCITY_TRANSITION, ISO_VELOCITY_STEADY_STATE]
